import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

await mkdir('artifacts', { recursive: true });
const browser = await chromium.launch({channel:'msedge', headless:true});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
const errors = [];
const base = process.env.PREVIEW_URL || 'http://localhost:3001';
page.on('pageerror', error => errors.push(error.message));
await page.goto(base, {waitUntil:'networkidle'});
await page.waitForTimeout(1800);
await page.screenshot({path:'artifacts/home-desktop.png',fullPage:true});
console.log('Title:',await page.title());
console.log('Hero visible:',await page.locator('.banner-one__title').isVisible());
console.log('Broken images:',await page.locator('img').evaluateAll(imgs=>imgs.filter(img=>!img.complete || img.naturalWidth===0).map(img=>img.src)));
await page.goto(base + '/track',{waitUntil:'networkidle'});
await page.locator('[name="tracking_number"]').fill('TRK-2026-000001');
await page.locator('button:has-text("Track Now")').click();
console.log('Tracking feedback:',await page.locator('[role="status"]').innerText());
await page.setViewportSize({width:390,height:844});
await page.goto(base,{waitUntil:'networkidle'});
await page.waitForTimeout(1000);
await page.locator('.mobile-nav__toggler').filter({visible:true}).first().click();
console.log('Mobile menu open:',await page.locator('.mobile-nav__wrapper').evaluate(el=>el.classList.contains('expanded')));
await page.screenshot({path:'artifacts/home-mobile.png',fullPage:false});
console.log('Horizontal overflow:',await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth));
console.log('JS errors:',errors);
await browser.close();
if(errors.length) process.exitCode = 1;
